"""
                Copyright (C) 2020 Theodoros Siklafidis

    This file is part of GRATIS.

    GRATIS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    GRATIS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GRATIS. If not, see <https://www.gnu.org/licenses/>.
"""

import json
from conf.general import STRINGS_PATH

with open(STRINGS_PATH) as f:
    try:
        STRINGS = json.load(f)
    except Exception:
        exit(1)

# Static label names
# Common
GRAPH_TYPE_MATRIX_TEXT = 'Adjacency Matrix'
GRAPH_TYPE_LIST_TEXT = 'Adjacency List'

# Menu
MENU_STRINGS = STRINGS['gui']['menu']
FILE_LABEL_TEXT = MENU_STRINGS['file_label_text']
FILE_SETTINGS_LABEL_TEXT = MENU_STRINGS['file_settings_label_text']
FILE_EXIT_LABEL_TEXT = MENU_STRINGS['file_exit_label_text']

# Main page
MAIN_PAGE_WIDGETS = STRINGS['gui']['pages']['main']['widgets']
GENERATE_AREA_BUTTON_TEXT = MAIN_PAGE_WIDGETS['generate_area_button_text']
ANALYZE_AREA_BUTTON_TEXT = MAIN_PAGE_WIDGETS['analyze_area_button_text']
VISUALIZE_AREA_BUTTON_TEXT = MAIN_PAGE_WIDGETS['visualize_area_button_text']
HISTORY_AREA_BUTTON_TEXT = MAIN_PAGE_WIDGETS['history_area_button_text']
EXIT_BUTTON_TEXT = MAIN_PAGE_WIDGETS['exit_button_text']

# Generate page
GENERATE_PAGE_STRINGS = STRINGS['gui']['pages']['generate']
GENERATE_PAGE_WIDGETS = GENERATE_PAGE_STRINGS['widgets']
GENERATE_PAGE_MESSAGES = GENERATE_PAGE_STRINGS['messages']
GENERATE_PAGE_MESSAGES_ERROR = GENERATE_PAGE_MESSAGES['error']
GENERATE_PAGE_MESSAGES_INFO = GENERATE_PAGE_MESSAGES['info']
GENERATE_PAGE_MESSAGES_SUCCESS = GENERATE_PAGE_MESSAGES['success']
GENERATE_PAGE_MESSAGES_WARNING = GENERATE_PAGE_MESSAGES['warning']
# Generate page widgets
GENERATE_PAGE_MAIN_LABEL_TEXT = GENERATE_PAGE_WIDGETS['main_label_text']
GENERATE_PAGE_SELECT_GRAPH_LABEL_TEXT = GENERATE_PAGE_WIDGETS['select_graph_label_text']
GENERATE_PAGE_INCREMENTAL_GROWTH_TEXT = GENERATE_PAGE_WIDGETS['incremental_growth_text']
GENERATE_PAGE_PREFERENTIAL_ATTACHMENT_TEXT = GENERATE_PAGE_WIDGETS['preferential_attachment_text']
GENERATE_PAGE_NUMBER_OF_VERTICES_LABEL_TEXT = GENERATE_PAGE_WIDGETS['number_of_vertices_label_text']
GENERATE_PAGE_GRAPH_DEGREE_LABEL_TEXT = GENERATE_PAGE_WIDGETS['graph_degree_label_text']
GENERATE_PAGE_NUMBER_OF_EDGES_LABEL_TEXT = GENERATE_PAGE_WIDGETS['number_of_edges_label_text']
GENERATE_PAGE_NUMBER_OF_INITIAL_NODES_LABEL_TEXT = GENERATE_PAGE_WIDGETS['number_of_initial_nodes_label_text']
GENERATE_PAGE_INITIAL_CONNECTIONS_PER_NODE_LABEL_TEXT = GENERATE_PAGE_WIDGETS['initial_connections_per_node_label_text']
GENERATE_PAGE_PROBABILITY_LABEL_TEXT = GENERATE_PAGE_WIDGETS['probability_label_text']
GENERATE_PAGE_SEED_LABEL_TEXT = GENERATE_PAGE_WIDGETS['seed_label_text']
GENERATE_PAGE_CLASSPATH_LABEL_TEXT = GENERATE_PAGE_WIDGETS['classpath_label_text']
GENERATE_PAGE_GENERATE_BUTTON_TEXT = GENERATE_PAGE_WIDGETS['generate_button_text']
GENERATE_PAGE_BACK_BUTTON_TEXT = GENERATE_PAGE_WIDGETS['back_button_text']
GENERATE_PAGE_EXIT_BUTTON_TEXT = GENERATE_PAGE_WIDGETS['exit_button_text']
GENERATE_PAGE_CANCEL_BUTTON_TEXT = GENERATE_PAGE_WIDGETS['cancel_button_text']
# Generate page messages
# Error
GENERATE_PAGE_VERTICES_NON_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR['vertices_non_zero']
GENERATE_PAGE_VERTICES_GREATER_THAN_ONE_ERROR = GENERATE_PAGE_MESSAGES_ERROR['vertices_greater_than_one']
GENERATE_PAGE_ADJACENCY_TYPE_SELECT_ERROR = GENERATE_PAGE_MESSAGES_ERROR['adjacency_type_select']
GENERATE_PAGE_GRAPH_DEGREE_GREATER_THAN_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR['graph_degree_greater_than_zero']
GENERATE_PAGE_INCREMENTAL_GROWTH_ONLY_ERROR = GENERATE_PAGE_MESSAGES_ERROR['incremental_growth_only']

GENERATE_PAGE_SCALE_FREE_PROPERTIES_ERROR = GENERATE_PAGE_MESSAGES_ERROR['scale_free_properties']
GENERATE_PAGE_SCALE_FREE_VERTICES_GREATER_THAN_ONE_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'scale_free_vertices_greater_than_one']
GENERATE_PAGE_SCALE_FREE_INITIAL_NODES_NON_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'initial_nodes_non_zero']
GENERATE_PAGE_SCALE_FREE_VERTICES_INITIAL_NODES_NUMBER_EQUAL_ONE_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'vertices_initial_nodes_number_equal_one']
GENERATE_PAGE_SCALE_FREE_VERTICES_LESS_THAN_INITIAL_NODES_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'vertices_less_than_initial_nodes']
GENERATE_PAGE_ER_PROBABILITY_GREATER_THAN_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR['probability_greater_than_zero']
GENERATE_PAGE_CUSTOM_ER_EDGES_GREATER_THAN_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_er_edges_greater_than_zero']
GENERATE_PAGE_CUSTOM_ER_PROBABILITY_GREATER_THAN_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'probability_greater_than_zero']
GENERATE_PAGE_CUSTOM_ER_INVALID_NUMBER_OF_EDGES_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_er_invalid_number_of_edges']

GENERATE_PAGE_CUSTOM_SCALE_FREE_PROPERTIES_ERROR = GENERATE_PAGE_MESSAGES_ERROR['custom_scale_free_properties']
GENERATE_PAGE_CUSTOM_SCALE_FREE_VERTICES_GREATER_THAN_ONE_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_scale_free_vertices_greater_than_one']
GENERATE_PAGE_CUSTOM_SCALE_FREE_MAX_NUMBER_OF_EDGES_GREATER_THAN_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_scale_free_max_number_of_edges_greater_than_zero']
GENERATE_PAGE_CUSTOM_SCALE_FREE_INVALID_NUMBER_OF_EDGES_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_scale_free_invalid_number_of_edges']
GENERATE_PAGE_CUSTOM_SCALE_FREE_INITIAL_NODES_NON_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'initial_nodes_non_zero']
GENERATE_PAGE_CUSTOM_SCALE_FREE_INITIAL_CONNECTIONS_PER_NODE_NON_ZERO_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'custom_scale_free_initial_connections_per_node_non_zero']
GENERATE_PAGE_CUSTOM_SCALE_FREE_VERTICES_INITIAL_NODES_NUMBER_EQUAL_ONE_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'vertices_initial_nodes_number_equal_one']
GENERATE_PAGE_CUSTOM_SCALE_FREE_VERTICES_LESS_THAN_INITIAL_NODES_ERROR = GENERATE_PAGE_MESSAGES_ERROR[
    'vertices_less_than_initial_nodes']
# Info
GENERATE_PAGE_GRAPH_CREATION_CANCEL_IN_PROGRESS_INFO = GENERATE_PAGE_MESSAGES_INFO['graph_creation_cancel_in_progress']
GENERATE_PAGE_GRAPH_CREATION_CANCEL_COMPLETED_INFO = GENERATE_PAGE_MESSAGES_INFO['graph_creation_cancel_completed']
GENERATE_PAGE_FULL_SCALE_FREE_GENERATE_INFO = GENERATE_PAGE_MESSAGES_INFO['full_scale_free_generate']
GENERATE_PAGE_CUSTOM_FULL_SCALE_FREE_GENERATE_INFO = GENERATE_PAGE_MESSAGES_INFO['custom_full_scale_free_generate']
# Success
GENERATE_PAGE_GRAPH_CREATION_SUCCESS = GENERATE_PAGE_MESSAGES_SUCCESS['graph_creation']
# Warning
GENERATE_PAGE_CUSTOM_ER_HOMOGENEOUS_WARNING = GENERATE_PAGE_MESSAGES_WARNING['custom_er_homogeneous']

# Analyze page
ANALYZE_PAGE_STRINGS = STRINGS['gui']['pages']['analyze']
ANALYZE_PAGE_WIDGETS = ANALYZE_PAGE_STRINGS['widgets']
ANALYZE_PAGE_MESSAGES = ANALYZE_PAGE_STRINGS['messages']
ANALYZE_PAGE_MESSAGES_ERROR = ANALYZE_PAGE_MESSAGES['error']
ANALYZE_PAGE_MESSAGES_INFO = ANALYZE_PAGE_MESSAGES['info']
ANALYZE_PAGE_MESSAGES_SUCCESS = ANALYZE_PAGE_MESSAGES['success']
ANALYZE_PAGE_MESSAGES_WARNING = ANALYZE_PAGE_MESSAGES['warning']
# Analyze page widgets
ANALYZE_PAGE_MAIN_LABEL_TEXT = ANALYZE_PAGE_WIDGETS['main_label_text']
ANALYZE_PAGE_SELECT_FILE_TYPE_LABEL_TEXT = ANALYZE_PAGE_WIDGETS['select_file_type_label_text']
ANALYZE_PAGE_CLASSPATH_LABEL_TEXT = ANALYZE_PAGE_WIDGETS['classpath_label_text']
ANALYZE_PAGE_CALCULATE_METRICS_LABEL_TEXT = ANALYZE_PAGE_WIDGETS['calculate_metrics_label_text']
ANALYZE_PAGE_GEODESIC_PATHS_CHECKBUTTON_TEXT = ANALYZE_PAGE_WIDGETS['geodesic_paths_checkbutton_text']
ANALYZE_PAGE_CLOSENESS_CENTRALITY_CHECKBUTTON_TEXT = ANALYZE_PAGE_WIDGETS['closeness_centrality_checkbutton_text']
ANALYZE_PAGE_BETWEENNESS_CENTRALITY_CHECKBUTTON_TEXT = ANALYZE_PAGE_WIDGETS['betweenness_centrality_checkbutton_text']
ANALYZE_PAGE_ANALYZE_BUTTON_TEXT = ANALYZE_PAGE_WIDGETS['analyze_button_text']
ANALYZE_PAGE_SAVE_OUTPUT_BUTTON_TEXT = ANALYZE_PAGE_WIDGETS['save_output_button_text']
ANALYZE_PAGE_BACK_BUTTON_TEXT = ANALYZE_PAGE_WIDGETS['back_button_text']
ANALYZE_PAGE_EXIT_BUTTON_TEXT = ANALYZE_PAGE_WIDGETS['exit_button_text']
ANALYZE_PAGE_CANCEL_BUTTON_TEXT = ANALYZE_PAGE_WIDGETS['cancel_button_text']
ANALYZE_PAGE_BROWSE_BUTTON_FALLBACK_TEXT = ANALYZE_PAGE_WIDGETS['browse_button_fallback_text']
# Analyze page messages
# Error
ANALYZE_PAGE_GENERATE_GRAPH_ERROR = ANALYZE_PAGE_MESSAGES_ERROR['generate_graph']
ANALYZE_PAGE_ANALYSIS_FAILED_ERROR = ANALYZE_PAGE_MESSAGES_ERROR['analysis_failed']
ANALYZE_PAGE_NO_AVAILABLE_OUTPUT_ERROR = ANALYZE_PAGE_MESSAGES_ERROR['no_available_output']
ANALYZE_PAGE_EITHER_ADJACENCY_MATRIX_OR_LIST_ERROR = ANALYZE_PAGE_MESSAGES_ERROR['either_adjacency_matrix_or_list']
# Info
ANALYZE_PAGE_CALCULATE_GEODESIC_PATHS_INFO = ANALYZE_PAGE_MESSAGES_INFO['calculate_geodesic_paths']
ANALYZE_PAGE_CALCULATE_CLOSENESS_CENTRALITY_INFO = ANALYZE_PAGE_MESSAGES_INFO['calculate_closeness_centrality']
ANALYZE_PAGE_CALCULATE_BETWEENNESS_CENTRALITY_INFO = ANALYZE_PAGE_MESSAGES_INFO['calculate_betweenness_centrality']
ANALYZE_PAGE_GRAPH_ANALYSIS_CANCEL_IN_PROGRESS_INFO = ANALYZE_PAGE_MESSAGES_INFO['graph_analysis_cancel_in_progress']
ANALYZE_PAGE_GRAPH_ANALYSIS_CANCEL_COMPLETED_INFO = ANALYZE_PAGE_MESSAGES_INFO['graph_analysis_cancel_completed']
# Success
ANALYZE_PAGE_CALCULATE_GEODESIC_PATHS_SUCCESS = ANALYZE_PAGE_MESSAGES_SUCCESS['calculate_geodesic_paths']
ANALYZE_PAGE_CALCULATE_CLOSENESS_CENTRALITY_SUCCESS = ANALYZE_PAGE_MESSAGES_SUCCESS['calculate_closeness_centrality']
ANALYZE_PAGE_CALCULATE_BETWEENNESS_CENTRALITY_SUCCESS = ANALYZE_PAGE_MESSAGES_SUCCESS[
    'calculate_betweenness_centrality']
ANALYZE_PAGE_LAST_GENERATED_GRAPH_ANALYSIS_SUCCESS = ANALYZE_PAGE_MESSAGES_SUCCESS['last_generated_graph_analysis']

# Visualize page
VISUALIZE_PAGE_STRINGS = STRINGS['gui']['pages']['visualize']
VISUALIZE_PAGE_WIDGETS = VISUALIZE_PAGE_STRINGS['widgets']
VISUALIZE_PAGE_MESSAGES = VISUALIZE_PAGE_STRINGS['messages']
VISUALIZE_PAGE_MESSAGES_ERROR = VISUALIZE_PAGE_MESSAGES['error']
VISUALIZE_PAGE_MESSAGES_INFO = VISUALIZE_PAGE_MESSAGES['info']
VISUALIZE_PAGE_MESSAGES_SUCCESS = VISUALIZE_PAGE_MESSAGES['success']
VISUALIZE_PAGE_MESSAGES_WARNING = VISUALIZE_PAGE_MESSAGES['warning']
# Visualize page widgets
VISUALIZE_PAGE_MAIN_LABEL_TEXT = VISUALIZE_PAGE_WIDGETS['main_label_text']
VISUALIZE_PAGE_PAJEK_BUTTON_TEXT = VISUALIZE_PAGE_WIDGETS['pajek_button_text']
VISUALIZE_PAGE_PLOTLY_BUTTON_TEXT = VISUALIZE_PAGE_WIDGETS['plotly_button_text']
VISUALIZE_PAGE_MATPLOTLIB_BUTTON_TEXT = VISUALIZE_PAGE_WIDGETS['matplotlib_button_text']
VISUALIZE_PAGE_BACK_BUTTON_TEXT = VISUALIZE_PAGE_WIDGETS['back_button_text']
VISUALIZE_PAGE_EXIT_BUTTON_TEXT = VISUALIZE_PAGE_WIDGETS['exit_button_text']
# Visualize page messages
# Error
VISUALIZE_PAGE_VISUALIZATION_VIA_MATRIX_LIST_ERROR = VISUALIZE_PAGE_MESSAGES_ERROR['visualization_via_matrix_list']
VISUALIZE_PAGE_3D_VISUALIZATION_VIA_MATRIX_LIST_ERROR = VISUALIZE_PAGE_MESSAGES_ERROR[
    '3d_visualization_via_matrix_list']
VISUALIZE_PAGE_VISUALIZATION_FAILED_ERROR = VISUALIZE_PAGE_MESSAGES_ERROR['visualization_failed']
VISUALIZE_PAGE_PLOTLY_FAILED_ERROR = VISUALIZE_PAGE_MESSAGES_ERROR['plotly_failed']
VISUALIZE_PAGE_PLOTLY_FAILED_NO_GRAPH_GENERATED_ERROR = VISUALIZE_PAGE_MESSAGES_ERROR[
    'plotly_failed_no_graph_generated']
# Info
VISUALIZE_PAGE_PLOTLY_WAIT_INFO = VISUALIZE_PAGE_MESSAGES_INFO['plotly_wait']
# Success
VISUALIZE_PAGE_VISUALIZATION_COMPLETED_SUCCESS = VISUALIZE_PAGE_MESSAGES_SUCCESS['visualization_completed']
VISUALIZE_PAGE_PLOTLY_GRAPH_CREATE_SUCCESS = VISUALIZE_PAGE_MESSAGES_SUCCESS['plotly_graph_create']

# History page
HISTORY_PAGE_STRINGS = STRINGS['gui']['pages']['history']
HISTORY_PAGE_WIDGETS = HISTORY_PAGE_STRINGS['widgets']
# History page widgets
HISTORY_PAGE_BACK_BUTTON_TEXT = HISTORY_PAGE_WIDGETS['back_button_text']
HISTORY_PAGE_DELETE_BUTTON_FALLBACK_TEXT = HISTORY_PAGE_WIDGETS['delete_button_fallback_text']
HISTORY_PAGE_MORE_BUTTON_FALLBACK_TEXT = HISTORY_PAGE_WIDGETS['more_button_fallback_text']
HISTORY_PAGE_LESS_BUTTON_FALLBACK_TEXT = HISTORY_PAGE_WIDGETS['less_button_fallback_text']

# Settings page
SETTINGS_PAGE_STRINGS = STRINGS['gui']['pages']['settings']
SETTINGS_PAGE_WIDGETS = SETTINGS_PAGE_STRINGS['widgets']
# Settings page widgets
SETTINGS_PAGE_THEMES_TAB_TEXT = SETTINGS_PAGE_WIDGETS['themes_tab_text']
SETTINGS_PAGE_LIGHT_THEME_BUTTON_TEXT = SETTINGS_PAGE_WIDGETS['light_theme_button_text']
SETTINGS_PAGE_DARK_THEME_BUTTON_TEXT = SETTINGS_PAGE_WIDGETS['dark_theme_button_text']

# CLI
ARGPARSE_HELP_STRINGS = STRINGS['cli']['help']
